server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: file-query-service
  
logging:
  level:
    com.example.filequery: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"